name: TC00_Entire_Test

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run tests with Maven
      run: mvn clean test -Dcucumber.filter.tags="@entiretest"

    - name: Upload Spark Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: SparkReport
        path: ExtentReports/**/Reports/
