

name: TC18_Today_Message_Send_Count

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: zeitblast-selenium-self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: TC18_todaymessagesendcount
      run: mvn clean test -Dcucumber.filter.tags="@todaymessagesendcount"
    - name: Upload Spark Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: SparkReport
        path: ExtentReports/**/Reports/
 
